BeerRoute/Models/Visita.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace BeerRoute.Models
{
    public class Visita
    {
        public int Id { get; set; }
        [Required]
        public int UsuarioId { get; set; }
        [Required]
        public Usuario Usuario { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime DataVisita { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Os créditos utilizados devem ser um valor positivo.")]
        public int CreditosUtilizados { get; set; }
        [Range(1, 5, ErrorMessage = "A avaliação deve estar entre 1 e 5.")]
        public int Avaliacao { get; set; }
        public string Comentario { get; set; }
        public ICollection<VisitaCervejaria> VisitaCervejarias { get; set; }
        public string ModoViagem { get; set; } //Adicionado para selecionar o modo viagem
    }
}

BeerRoute/Controllers/VisitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerRoute.Data;
using BeerRoute.Models;
using BeerRoute.Models.ViewModels;
using Microsoft.Extensions.Configuration;

namespace BeerRoute.Controllers
{
    public class VisitasController : Controller
    {
        private readonly BeerRouteContext _context;
        private readonly IConfiguration _configuration;

        public VisitasController(BeerRouteContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        // GET: Visitas
        public async Task<IActionResult> Index()
        {
            var beerRouteContext = _context.Visita
                .Include(v => v.Usuario)
                .Include(v => v.VisitaCervejarias)
                    .ThenInclude(vc => vc.Cervejaria);
            ViewBag.ApiKey = _configuration["ApiSettings:ApiKey"];
            return View(await beerRouteContext.ToListAsync());
        }

        // GET: Visitas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Visita == null)
            {
                return NotFound();
            }

            var visita = await _context.Visita
                .Include(v => v.Usuario)
                .Include(v => v.VisitaCervejarias)
                    .ThenInclude(vc => vc.Cervejaria)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visita == null)
            {
                return NotFound();
            }

            return View(visita);
        }

        // GET: Visitas/Create
        public IActionResult Create()
        {
            ViewData["UsuarioId"] = new SelectList(_context.Usuario, "Id", "Nome");
            var estilosCerveja = _context.TipoCerveja.Select(tc => tc.Estilo).Distinct().ToList();
            estilosCerveja.Insert(0, "Selecione um estilo de Cerveja");
            ViewData["EstiloCerveja"] = new SelectList(estilosCerveja);
            ViewData["CervejariaIds"] = new SelectList(Enumerable.Empty<SelectListItem>(), "Id", "Nome");
            return View();
        }

        // POST: Visitas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UsuarioId,DataVisita,CreditosUtilizados,Avaliacao,Comentario,EstiloCerveja,CervejariaIds,ModoViagem")] ViewModelVisita visitaViewModel)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _context.Usuario.FindAsync(visitaViewModel.UsuarioId);
                if (usuario == null)
                {
                    return NotFound();
                }

                if (usuario.Creditos < visitaViewModel.CreditosUtilizados)
                {
                    ModelState.AddModelError(string.Empty, "Créditos insuficientes. Por favor, adicione mais créditos para concluir a visita.");
                    ViewData["UsuarioId"] = new SelectList(_context.Usuario, "Id", "Nome", visitaViewModel.UsuarioId);
                    ViewData["EstiloCerveja"] = new SelectList(_context.TipoCerveja.Select(tc => tc.Estilo).Distinct(), visitaViewModel.EstiloCerveja);
                    ViewData["CervejariaIds"] = new SelectList(_context.CervejariaTipoCerveja.Where(ctc => ctc.TipoCerveja.Estilo == visitaViewModel.EstiloCerveja).Select(ctc => ctc.Cervejaria), "Id", "Nome", visitaViewModel.CervejariaIds);
                    return View(visitaViewModel);
                }

                var visita = new Visita
                {
                    UsuarioId = visitaViewModel.UsuarioId,
                    DataVisita = visitaViewModel.DataVisita,
                    CreditosUtilizados = visitaViewModel.CreditosUtilizados,
                    Avaliacao = visitaViewModel.Avaliacao,
                    Comentario = visitaViewModel.Comentario,
                    VisitaCervejarias = visitaViewModel.CervejariaIds.Select(id => new VisitaCervejaria { CervejariaId = id }).ToList(),
                    ModoViagem = visitaViewModel.ModoViagem
                };

                _context.Add(visita);
                await _context.SaveChangesAsync();

                // Descontar os créditos do usuário
                usuario.Creditos -= visita.CreditosUtilizados;
                _context.Update(usuario);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.Usuario, "Id", "Nome", visitaViewModel.UsuarioId);
            ViewData["EstiloCerveja"] = new SelectList(_context.TipoCerveja.Select(tc => tc.Estilo).Distinct(), visitaViewModel.EstiloCerveja);
            ViewData["CervejariaIds"] = new SelectList(_context.CervejariaTipoCerveja.Where(ctc => ctc.TipoCerveja.Estilo == visitaViewModel.EstiloCerveja).Select(ctc => ctc.Cervejaria), "Id", "Nome", visitaViewModel.CervejariaIds);
            return View(visitaViewModel);
        }

        public JsonResult GetCervejariasByEstiloCerveja(string estiloCerveja)
        {
            var cervejarias = _context.CervejariaTipoCerveja
                .Where(ctc => ctc.TipoCerveja.Estilo == estiloCerveja)
                .Select(ctc => new { ctc.Cervejaria.Id, ctc.Cervejaria.Nome })
                .ToList();
            return Json(cervejarias);
        }

        // GET: Visitas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Visita == null)
            {
                return NotFound();
            }

            var visita = await _context.Visita
                .Include(v => v.VisitaCervejarias)
                .ThenInclude(vc => vc.Cervejaria)
                .ThenInclude(c => c.CervejariaTiposCervejas)
                .ThenInclude(ctc => ctc.TipoCerveja)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visita == null)
            {
                return NotFound();
            }

            var estiloCerveja = visita.VisitaCervejarias
                .SelectMany(vc => vc.Cervejaria.CervejariaTiposCervejas)
                .Select(ctc => ctc.TipoCerveja.Estilo)
                .FirstOrDefault();

            var visitaViewModel = new ViewModelVisita
            {
                Id = visita.Id,
                UsuarioId = visita.UsuarioId,
                DataVisita = visita.DataVisita,
                CreditosUtilizados = visita.CreditosUtilizados,
                Avaliacao = visita.Avaliacao,
                Comentario = visita.Comentario,
                EstiloCerveja = estiloCerveja ?? string.Empty,
                CervejariaIds = visita.VisitaCervejarias?.Select(vc => vc.CervejariaId).ToList() ?? new List<int>(),
                ModoViagem = visita.ModoViagem
            };

            ViewData["UsuarioNome"] = _context.Usuario.FirstOrDefault(u => u.Id == visita.UsuarioId)?.Nome;
            ViewData["CervejariaIds"] = new SelectList(_context.CervejariaTipoCerveja.Where(ctc => ctc.TipoCerveja.Estilo == visitaViewModel.EstiloCerveja).Select(ctc => ctc.Cervejaria), "Id", "Nome", visitaViewModel.CervejariaIds);
            return View(visitaViewModel);
        }

        // POST: Visitas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UsuarioId,DataVisita,CreditosUtilizados,Avaliacao,Comentario,CervejariaIds,ModoViagem")] ViewModelVisita visitaViewModel)
        {
            if (id != visitaViewModel.Id)
            {
                return NotFound();
            }

            var visita = await _context.Visita
                .Include(v => v.VisitaCervejarias)
                .FirstOrDefaultAsync(v => v.Id == id);

            if (visita == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(visita.UsuarioId);
            if (usuario == null)
            {
                return NotFound();
            }

            // Verificar se o usuário tem créditos suficientes
            var creditosNecessarios = visitaViewModel.CreditosUtilizados - visita.CreditosUtilizados;
            if (usuario.Creditos < creditosNecessarios)
            {
                ModelState.AddModelError(string.Empty, "Créditos insuficientes. Por favor, adicione mais créditos para concluir a visita.");
                ViewData["UsuarioNome"] = _context.Usuario.FirstOrDefault(u => u.Id == visita.UsuarioId)?.Nome;
                ViewData["CervejariaIds"] = new SelectList(_context.CervejariaTipoCerveja.Where(ctc => ctc.TipoCerveja.Estilo == visitaViewModel.EstiloCerveja).Select(ctc => ctc.Cervejaria), "Id", "Nome", visitaViewModel.CervejariaIds);
                return View(visitaViewModel);
            }

            // Ajustar os créditos do usuário
            usuario.Creditos += visita.CreditosUtilizados; // Reverter os créditos antigos
            usuario.Creditos -= visitaViewModel.CreditosUtilizados; // Aplicar os novos créditos

            visita.UsuarioId = visitaViewModel.UsuarioId;
            visita.DataVisita = visitaViewModel.DataVisita;
            visita.CreditosUtilizados = visitaViewModel.CreditosUtilizados;
            visita.Avaliacao = visitaViewModel.Avaliacao;
            visita.Comentario = visitaViewModel.Comentario;
            visita.VisitaCervejarias = visitaViewModel.CervejariaIds.Select(cid => new VisitaCervejaria { CervejariaId = cid }).ToList();
            visita.ModoViagem = visitaViewModel.ModoViagem;

            _context.Update(visita);
            _context.Update(usuario);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Visitas/Delete/5
        public async Task<IActionResult> Delete(int? id)

BeerRoute/Views/Visitas/Create.cshtml
@model BeerRoute.Models.ViewModels.ViewModelVisita

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar</h1>

<hr />
<div class="row">
    <div class="col-md-6 col-lg-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (ViewData.ModelState.ErrorCount > 0)
            {
                <div class="alert alert-danger">
                    @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                    {
                        <p>@error.ErrorMessage</p>
                    }
                </div>
            }
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label">Usuário</label>
                <select asp-for="UsuarioId" class="form-control" asp-items="ViewBag.UsuarioId"></select>
                <span asp-validation-for="UsuarioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstiloCerveja" class="control-label">Estilo de Cerveja</label>
                <select asp-for="EstiloCerveja" class="form-control" asp-items="ViewBag.EstiloCerveja" id="estiloCervejaSelect"></select>
                <span asp-validation-for="EstiloCerveja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CervejariaIds" class="control-label">Cervejarias</label>
                <select asp-for="CervejariaIds" class="form-control" asp-items="ViewBag.CervejariaIds" multiple id="cervejariaSelect"></select>
                <span asp-validation-for="CervejariaIds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataVisita" class="control-label">Data da Visita</label>
                <input asp-for="DataVisita" class="form-control" />
                <span asp-validation-for="DataVisita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditosUtilizados" class="control-label">Créditos Gastos</label>
                <input asp-for="CreditosUtilizados" class="form-control" />
                <span asp-validation-for="CreditosUtilizados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label">Avaliação</label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label">Comentário</label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModoViagem" class="control-label">Modo de Viagem</label>
                <select asp-for="ModoViagem" class="form-control">
                    <option value="DRIVING">Carro</option>
                    <option value="WALKING">A pé</option>
                </select>
                <span asp-validation-for="ModoViagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar para a Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $('#estiloCervejaSelect').change(function () {
                var estiloCerveja = $(this).val();
                $.getJSON('@Url.Action("GetCervejariasByEstiloCerveja", "Visitas")', { estiloCerveja: estiloCerveja }, function (data) {
                    var items = '<option value="">Selecione uma Cervejaria</option>';
                    $.each(data, function (i, cervejaria) {
                        items += '<option value="' + cervejaria.id + '">' + cervejaria.nome + '</option>';
                    });
                    $('#cervejariaSelect').html(items);
                });
            });
        });
    </script>
}

BeerRoute/Views/Visitas/Delete.cshtml
@model BeerRoute.Models.Visita

@{
    ViewData["Title"] = "Excluir";
}

<h1>Excluir Visita</h1>

<h3>Tem certeza de que deseja excluir esta visita?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Usuário</dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Nome)
        </dd>
        <dt class="col-sm-2">Cervejarias</dt>
        <dd class="col-sm-10">
            @foreach (var cervejaria in Model.VisitaCervejarias)
            {
                <p>@cervejaria.Cervejaria.Nome</p>
            }
        </dd>
        <dt class="col-sm-2">Data da Visita</dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataVisita)
        </dd>
        <dt class="col-sm-2">Créditos Gastos</dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreditosUtilizados)
        </dd>
        <dt class="col-sm-2">Avaliação</dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao)
        </dd>
        <dt class="col-sm-2">Comentário</dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" />
        <a class="btn btn-secondary" asp-action="Index">Voltar para a Lista</a>
    </form>
</div>

BeerRoute/Views/Visitas/Details.cshtml
@model BeerRoute.Models.Visita

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div> 
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Nome)
        </dd>
        <dt class="col-sm-2">
            Cervejarias
        </dt>
        <dd class="col-sm-10">
            @foreach (var cervejaria in Model.VisitaCervejarias)
            {
                <p>@cervejaria.Cervejaria.Nome</p>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataVisita)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataVisita)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreditosUtilizados)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreditosUtilizados)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Editar</a>
    <a class="btn btn-secondary" asp-action="Index">Voltar para a Lista</a>
</div>

BeerRoute/Views/Visitas/Edit.cshtml
@model BeerRoute.Models.ViewModels.ViewModelVisita

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-6 col-lg-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (ViewData.ModelState.ErrorCount > 0)
            {
                <div class="alert alert-danger">
                    @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
                    {
                        <p>@error.ErrorMessage</p>
                    }
                </div>
            }
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UsuarioId" />
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label">Usuário</label>
                <input type="text" class="form-control" value="@ViewBag.UsuarioNome" disabled />
            </div>
            <div class="form-group">
                <label asp-for="EstiloCerveja" class="control-label">Estilo de Cerveja</label>
                <input type="text" class="form-control" value="@Model.EstiloCerveja" disabled />
            </div>
            <div class="form-group">
                <label asp-for="CervejariaIds" class="control-label">Cervejarias</label>
                <select asp-for="CervejariaIds" class="form-control" asp-items="ViewBag.CervejariaIds" multiple disabled></select>
                <span asp-validation-for="CervejariaIds" class="text-danger"></span>
                @foreach (var cervejariaId in Model.CervejariaIds)
                {
                    <input type="hidden" name="CervejariaIds" value="@cervejariaId" />
                }
            </div>
            <div class="form-group">
                <label asp-for="DataVisita" class="control-label">Data da Visita</label>
                <input asp-for="DataVisita" class="form-control" />
                <span asp-validation-for="DataVisita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditosUtilizados" class="control-label">Créditos Utilizados</label>
                <input asp-for="CreditosUtilizados" class="form-control" />
                <span asp-validation-for="CreditosUtilizados" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label">Avaliação</label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label">Comentário</label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModoViagem" class="control-label">Modo de Viagem</label>
                <select asp-for="ModoViagem" class="form-control">
                    <option value="DRIVING">Carro</option>
                    <option value="WALKING">A pé</option>
                </select>
                <span asp-validation-for="ModoViagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Voltar para a Lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BeerRoute/Views/Visitas/Index.cshtml
@model IEnumerable<BeerRoute.Models.Visita>

@{
    ViewData["Title"] = "Marcando uma Visita";
    var apiKey = ViewBag.ApiKey;
    var userLat = -30.03488;
    var userLng = -51.22647;
    var beerIconUrl = Url.Content("~/images/lupuloicon.svg"); // Caminho para o ícone lúpulo em formato SVG
}

<h1>Marcando uma Visita</h1>

<p>
    <a class="btn btn-success mb-3" asp-action="Create">Criar Novo</a>
</p>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Usuário</th>
                <th>Cervejarias</th>
                <th>Data da Visita</th>
                <th>Créditos Gastos</th>
                <th>Avaliação</th>
                <th>Comentário</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Usuario.Nome</td>
                    <td>
                        @foreach (var cervejaria in item.VisitaCervejarias)
                        {
                            <p>@cervejaria.Cervejaria.Nome</p>
                        }
                    </td>
                    <td>@item.DataVisita</td>
                    <td>@item.CreditosUtilizados</td>
                    <td>@item.Avaliacao</td>
                    <td>@item.Comentario</td>
                    <td>
                        <a class="btn btn-primary btn-sm mb-1" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                        <a class="btn btn-info btn-sm mb-1" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                        <a class="btn btn-danger btn-sm mb-1" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div id="map" style="height: 500px; width: 100%; margin-top: 20px;"></div>

<script src="https://maps.googleapis.com/maps/api/js?key=@apiKey&callback=initMap" async defer></script>
<script>
    var map;
    var directionsService;
    var directionsRenderer;
    var beerIconUrl = '@beerIconUrl';

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: { lat: @userLat, lng: @userLng },
            zoom: 15
        });
        directionsService = new google.maps.DirectionsService();
        directionsRenderer = new google.maps.DirectionsRenderer({
            suppressMarkers: true // Suprime os marcadores padrão
        });
        directionsRenderer.setMap(map);
        calculateAndDisplayRoute();
    }

    function calculateAndDisplayRoute() {
        var waypoints = [];
        var markers = [];
        var infoWindows = [];
        var order = 1;

    @foreach (var item in Model)
    {
        @foreach (var cervejaria in item.VisitaCervejarias)
        {
            <text>
                            waypoints.push({
                                location: new google.maps.LatLng(@cervejaria.Cervejaria.Latitude, @cervejaria.Cervejaria.Longitude),
                                stopover: true
                            });

                            var marker = new google.maps.Marker({
                                position: { lat: @cervejaria.Cervejaria.Latitude, lng: @cervejaria.Cervejaria.Longitude },
                                map: map,
                                title: '@cervejaria.Cervejaria.Nome' + ' - ' + '@cervejaria.Cervejaria.Endereco',
                                icon: {
                                    url: beerIconUrl,
                                    scaledSize: new google.maps.Size(48, 48), // Ajuste o tamanho do ícone aqui
                                    labelOrigin: new google.maps.Point(24, -10) // Ajuste a posição do rótulo aqui
                                },
                                label: {
                                    text: order.toString(),
                                    color: 'red',
                                    fontSize: '16px',
                                    fontWeight: 'bold'
                                }
                            });

                            var infoWindow = new google.maps.InfoWindow({
                                content: '<div><strong>@cervejaria.Cervejaria.Nome</strong></div>'
                            });

                            google.maps.event.addListener(marker, 'click', (function(marker, infoWindow) {
                                return function() {
                                    infoWindows.forEach(function(iw) { iw.close(); });
                                    infoWindow.open(map, marker);
                                };
                            })(marker, infoWindow));

                            markers.push(marker);
                            infoWindows.push(infoWindow);
                            order++;
            </text>
        }
    }

        if (waypoints.length < 1) {
            return;
        }

        var start = { lat: @userLat, lng: @userLng };
        var end = waypoints.pop().location;
        var travelMode = '@Model.FirstOrDefault()?.ModoViagem' || 'DRIVING'; // Default to DRIVING if not set

        // Adiciona o marcador para o ponto de partida
        var startMarker = new google.maps.Marker({
            position: start,
            map: map,
            title: 'Ponto de Partida'
        });

        var startInfoWindow = new google.maps.InfoWindow({
            content: '<div><strong>@Model.FirstOrDefault()?.Usuario.Nome</strong></div>'
        });

        startMarker.addListener('click', function() {
            infoWindows.forEach(function(iw) { iw.close(); });
            startInfoWindow.open(map, startMarker);
        });

        infoWindows.push(startInfoWindow);

        directionsService.route(
            {
                origin: start,
                destination: end,
                waypoints: waypoints,
                optimizeWaypoints: true, // Otimiza a ordem dos waypoints
                travelMode: google.maps.TravelMode[travelMode]
            },
            function(response, status) {
                if (status === google.maps.DirectionsStatus.OK) {
                    directionsRenderer.setDirections(response);
                } else {
                    window.alert('Directions request failed due to ' + status);
                }
            }
        );
    }
</script>